import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './styles/global.css';
import './styles/readability.css';
import './styles/air-hockey.css';
import './styles/night-shift.css';
import './styles/responsive.css';
import './styles/circuit-break.css';
import './styles/retro-menu.css';
import './styles/silly-fish.css';
import './styles/retro-back-sign.css';
import './styles/play-cabinets.css';
import './styles/title-menu-transition.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
